ds:
  db:
    host: 127.0.0.1
    database: ds_user
    un: root
    pw: 123456
  redis:
    host: 127.0.0.1
    port: 6379
    password:
spring:
  mail:
    host: smtp.163.com
    #服务协议
    protocol: smtp
    # 编码集
    default-encoding: UTF-8
    #发送邮件的账户
    username: writiger@163.com
    #授权码
    password:
    test-connection: true
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true