server:
  port: 18080
spring:
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          filters:
            # 解决跨域问题
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
          predicates:
            - Path=/user/**,/admin/**
        - id: belong-service
          uri: lb://belong-service
          predicates:
            - Path=/belong/**
        - id: doc-service
          uri: lb://doc-service
          predicates:
            - Path=/doc/**
        - id: file-service
          uri: lb://file-service
          predicates:
            - Path=/file/**
ds:
  jwt:
    location: classpath:ds.jks
    alias: dlnu
    password: 123456
    tokenTTL: 10080m
  auth:
    excludePaths:
      - /user/login
      - /user/register
      - /user/verify/**
      - /belong/list
      - /doc/search/**
      - /file/**