server:
  port: 18084
pro:
  uploadPath: uploads/
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  application:
    name: file-service
  okhttp:
    enabled: true
  mvc:
    static-path-pattern: "/resources/**"
  web:
    resources:
      static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,classpath:uploads/
ds:
  swagger:
    title: 文件服务接口文档
    package: com.ds.file.controller
  web:
    url: http://127.0.0.1:3000
